UI/HQue.WebCore/Controllers/Setup/InstanceSetupController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HQue.Contract.Infrastructure;
using HQue.Contract.Infrastructure.Setup;
using HQue.Biz.Core.Setup;
using Utilities.Helpers;

namespace HQue.WebCore.Controllers.Setup
{
    [Route("[controller]")]
    public class InstanceSetupController : BaseController
    {
        private readonly InstanceSetupManager _instanceSetupManager;
        private readonly ConfigHelper _configHelper;

        public InstanceSetupController(InstanceSetupManager instanceSetupManager, ConfigHelper configHelper) : base(configHelper)
        {
            _instanceSetupManager = instanceSetupManager;
            _configHelper = configHelper;
        }

        [Route("[action]")]
        public async Task<ViewResult> Index()
        {
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/Dashboard");
            }
            ViewBag.InstanceCount = Convert.ToInt32(await _instanceSetupManager.GetInstanceCount(User.AccountId()));
            return View();
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> Index([FromBody]Instance model)
        {
            // if (!ModelState.IsValid)
            //     return View(model);

            model.SetLoggedUserDetails(User);

            var id = model.InstanceId;

            model = await _instanceSetupManager.Save(model);
            return View(model);
        }

        [Route("[action]")]
        public async Task<IActionResult> List()
        {
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/Dashboard");
            }
            ViewBag.InstanceCount = Convert.ToInt32(await _instanceSetupManager.GetInstanceCount(User.AccountId()));
            ViewBag.TotalInstanceCount = Convert.ToInt32(await _instanceSetupManager.GetTotalInstanceCount(User.AccountId()));
            
            return View();
        }

        [Route("[action]")]
        public async Task<PagerContract<Instance>> ListData([FromBody]Instance model)
        {
            model.SetLoggedUserDetails(User);
            return await _instanceSetupManager.ListPager(model);
        }


        [Route("[action]")]
        public IActionResult Update(string id)
        {
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/Dashboard");
            }
            if (id != null)
            {
                ViewBag.Id = id;
            }
            return View();
        }

        [Route("[action]")]
        public async Task<Instance> GetById(string instanceId)
        {
            return await _instanceSetupManager.GetById(instanceId);
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<Instance> UpdateInstance([FromBody]Instance model)
        {
            model.SetLoggedUserDetails(User);
            await _instanceSetupManager.UpdateInstance(model);

            return model;
        }
    }
}

UI/HQue.WebCore/Views/InstanceSetup/List.cshtml
@{
    ViewBag.Title = "Pharmacy List";
}

@await Html.PartialAsync("~/Views/InstanceSetup/Menu.cshtml")

<div class="row panelBorder" ng-app="hcue" ng-controller="instanceSetupSearchCtrl" ng-cloak>
    <div class="panel panel-default">
        @*<div class="panel-heading">Branch Search</div>*@
        <div class="panel-body">
            <div class='row'>
                <div class='col-sm-2'>
                    <div class='form-group'>
                        <div class="input-group">
                            <label>Branch Name</label>
                            <input title="Pharmacy Name" type="text" placeholder="Branch Name" class="search-query form-control" ng-enter="pharmacySearch()" ng-model="search.name" autofocus>
                        </div>
                    </div>
                </div>
                <div class='col-sm-2'>
                    <div class='form-group'>
                        <div class="input-group">
                            <label>Mobile No.</label>
                            @*<input title="Phone Number" type="text" placeholder="Phone" class="search-query form-control" ng-enter="pharmacySearch()" ng-model="search.phone">*@
                            <input title="Mobile Number" type="text" placeholder="Mobile" class="search-query form-control" ng-enter="pharmacySearch()" ng-model="search.mobile">
                        </div>
                    </div>
                </div>

                <div class='col-sm-1'>
                    <div class='form-group'>
                        <div class="input-group">
                            <label class='col-md-12'>&nbsp;&nbsp;&nbsp;&nbsp;</label>
                            <button title="Search" class="btn btn-style" ng-click="pharmacySearch()">Search</button>

                        </div>
                    </div>
                </div>
                <div class='col-sm-2 pull-right'>
                    <div class='form-group'>
                        <div class="input-group">
                            <label class='col-md-12'>&nbsp;&nbsp;&nbsp;&nbsp;</label>
                            <strong>No. of Licenses: @ViewBag.TotalInstanceCount</strong>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        @*<div class="panel-footer clearfix">
                <div class="pull-left" ng-if="list.length == 0">
                    No Records found
                </div>

            </div>*@
    </div>
    @if (ViewBag.InstanceCount > 0)
    {
        @if (!ViewBag.Config.AppConfig.OfflineMode)
        {
            <a ng-href="/Registration/Branch" onclick="window.open(this.href); return false;" class="btn  btn-style text-center" title="Buy">Add New Branch</a>
            <br />
            <br />
        }
    }
    else
    {
        <div class="row marginLR-zero">
            <p>You have reached the limit of your licence, contact hcue admin for further information.</p>
        </div>
    }
    <div class="panel panel-default">
        @*<div class="panel-heading">Sales List</div>*@
        <div class="panel-body">
            <div class='row  marginLR-zero'>
                @*{{list}}*@
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="datatable">
                    <thead>
                        <tr>
                            <th>Action</th>
                            <th>Branch Code</th>
                            <th>Branch Name</th>
                            <th>Mobile</th>
                            <th>Address</th>
                            <th>GSTIN No</th>
                            <th>Registered Date</th>
                            @*<th>Action</th>*@

                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="pharmacy in list | orderBy: 'code' track by $index">
                            @if (!ViewBag.Config.AppConfig.OfflineMode)
                            {
                                <td>
                                    <span>
                                        @*<a ng-href="/InstanceSetup/update?id={{pharmacy.id}}" class="btn  btn-style text-center" title="Buy">Edit</a>*@
                                        <a ng-href="/Registration/Branch?InstanceId={{pharmacy.id}}" onclick="window.open(this.href); return false;" class="btn  btn-style text-center" title="Buy">Edit</a>
                                    </span>
                                </td>
                            }
                            @if (ViewBag.Config.AppConfig.OfflineMode)
                            {
                                <td>
                                    <span>
                                        <a ng-click="openBranchForUpdate(pharmacy.id)" class="btn btn-style text-center" title="Buy">Edit</a>
                                    </span>
                                </td>
                            }
                            <td>{{pharmacy.code}}</td>
                            <td>{{pharmacy.name}} <span style="color:#039394;font-weight:bold;" ng-if="pharmacy.isHeadOffice==1"> (Head office)</span></td>
                            <td>{{pharmacy.mobile}}</td>
                            <td>{{pharmacy.fullAddress}}</td>
                            <td>{{pharmacy.gsTinNo}}</td>
                            <td>{{pharmacy.registrationDate | date:'dd/MM/yyyy' }}</td>
                            @*<td>View</td>*@
                        </tr>
                    </tbody>
                </table>
            </div>
            @{ await Html.RenderPartialAsync("~/views/shared/_pagination.cshtml"); }
        </div>
    </div>
    @{
        await Html.RenderPartialAsync("_hCueSupportLogin.cshtml");
    }
</div>

@section scripts
{
    <script asp-append-version="true" src="~/assets/js/angular.js"></script>
    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.min.js"></script>
    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.tpls.min.js"></script>
    <script asp-append-version="true" src="~/appScript/common/angular-common.js"></script>
    <script asp-append-version="true" src="~/appscript/common/ui-bootstrap-tpls-1.0.0.min.js"></script>
    <script asp-append-version="true" src="~/appscript/angular-modal-service.js"></script>

    <script asp-append-version="true" src="~/appscript/appScriptVendor.js"></script>
    <script asp-append-version="true" src="~/appscript/model.js"></script>
    <script asp-append-version="true" src="~/appscript/common/pagerservcie.js"></script>
    <script asp-append-version="true" src="~/appscript/instancesetup/instancesetupservice.js"></script>
    <script asp-append-version="true" src="~/appscript/instancesetup/instancesetupsearchctrl.js"></script>
    <script asp-append-version="true" src="~/appscript/instancesetup/hCueSupportLoginCtrl.js"></script>
}

UI/HQue.WebCore/Views/InstanceSetup/Menu.cshtml
<ul class="nav nav-tabs override_margin">
    @*<li class="@(ViewBag.Menu == "Pharmacy" ? "active" : "")">
        <a asp-action="Index" asp-controller="InstanceSetup">
            BRANCH
        </a>
    </li>*@
    <li class="@(ViewBag.Title == "Pharmacy List" ? "active" : "")">
        <a asp-action="List" asp-controller="InstanceSetup">
            LIST
        </a>
    </li>
</ul>

UI/HQue.WebCore/Views/InstanceSetup/Update.cshtml
@model HQue.Contract.Infrastructure.Setup.Instance
@{
    ViewBag.Title = "Edit Branch";
    ViewBag.Menu = "Pharmacy";
    Layout = "_Layout";
}

@await Html.PartialAsync("~/Views/InstanceSetup/Menu.cshtml")

<div class="row panelBorder" ng-app="hcue" ng-controller="updateInstanceCtrl" ng-cloak>
    <!-- Account Create Section - start -->
    <ng-form id="instanceUser" name="instanceUser">
        <div ng-init="init('@ViewBag.Id')"></div>

        <div class="panel panel-default">
            @*<div class="panel-heading">Edit Branch Information</div>*@
            <div class="panel-body">
                <div class='row'>
                    <div class='col-sm-2 '>
                        <div class='form-group'>
                            <div class="input-group  col-sm-12">
                                <label>Branch Name*</label>
                                <input title="Branch Name" id="branchName" name="branchName" type="text" placeholder="Branch Name" class="search-query form-control" maxlength="150" required ng-model="instance.name" autofocus>
                            </div>
                            <span class="error" ng-show="instanceUser.branchName.$dirty && instanceUser.branchName.$error.required">
                                Required!
                            </span>
                        </div>
                    </div>

                    <div class='col-sm-2 override_margin'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12 override_margin">
                                <label>Registration Date*</label>
                                <input type="text" id="registrationDate" name="registrationDate" required class="form-control" uib-datepicker-popup="{{format}}" placeholder="Registration Date" ng-model="instance.registrationDate" is-open="popup1.opened" min-date="minDate" max-date="maxDate" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text="Close" alt-input-formats="altInputFormats" my-date />
                                <span class="input-group-btn wrapper-date">
                                    <button type="button" class="btn btn-default btn1 size" ng-click="open1()">
                                        <i class="glyphicon glyphicon-calendar"></i>
                                    </button>
                                </span>
                            </div>
                            <span class="error" ng-show="instanceUser.registrationDate.$dirty && instanceUser.registrationDate.$error.required">
                                Required!
                            </span>
                        </div>
                    </div>

                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>Landline No.*</label>
                                <input title="Mobile Number" id="phone" name="phone" type="text" placeholder="Mobile" maxlength="15" class="search-query form-control" required ng-model="instance.phone" valid-number>
                            </div>
                            <span class="error" ng-show="instanceUser.phone.$dirty && instanceUser.phone.$error.required">
                                Required!
                            </span>
                        </div>
                    </div>
                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>Mobile No</label>
                                <input title="Mobile Number" id="mobile" name="mobile" type="text" placeholder="Mobile" maxlength="10" class="search-query form-control" ng-model="instance.mobile" valid-number>
                            </div>
                        </div>
                    </div>

                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>Drug License No.</label>
                                <input title="Drug License No" id="DrugLicenseNo" name="DrugLicenseNo" type="text" placeholder="Drug License No" class="search-query form-control" ng-model="instance.drugLicenseNo">
                            </div>
                        </div>
                    </div>
                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>TIN No.</label>
                                <input title="Tin No" id="TinNo" name="TinNo" type="text" placeholder="Tin No" class="search-query form-control" ng-model="instance.tinNo">
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>Address</label>
                                <input title="Address" id="address" name="address" placeholder="Address" class="form-control" ng-model="instance.address" />
                            </div>
                        </div>
                    </div>
                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>Area</label>
                                <input title="Area" id="Area" name="Area" type="text" placeholder="Area" class="search-query form-control" ng-model="instance.area">
                            </div>
                        </div>
                    </div>
                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>Landmark</label>
                                <input title="Landmark" id="Landmark" name="Landmark" type="text" placeholder="Landmark" class="search-query form-control" ng-model="instance.landmark">
                            </div>
                        </div>
                    </div>
                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>City</label>
                                <input title="City" id="City" name="City" type="text" placeholder="City" class="search-query form-control" ng-model="instance.city">
                            </div>
                        </div>
                    </div>
                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>State</label>
                                <input title="State" id="State" name="State" type="text" placeholder="State" class="search-query form-control" ng-model="instance.state">
                            </div>
                        </div>
                    </div>
                    <div class='col-sm-2'>
                        <div class='form-group'>
                            <div class="input-group col-sm-12">
                                <label>Pin Code</label>
                                <input title="Pincode" id="Pincode" name="Pincode" type="text" placeholder="Pincode" class="search-query form-control" ng-model="instance.pincode">
                            </div>
                        </div>
                    </div>
                </div>
           <div class="row">
               <div class='col-sm-2'>
                   <div class='form-group'>
                       <div class="input-group col-sm-12">
                           <label>Contact Name</label>
                           <input title="Contact Name" id="ContactName" name="ContactName" type="text" placeholder="Contact Name" class="search-query form-control" ng-model="instance.contactName">
                       </div>
                   </div>
               </div>
           </div>
             </div>
        </div>

        <div class="panel-footer clearfix">
            <div class="pull-right">
                <button title="Create" class="btn btn-style" ng-disabled="instanceUser.$invalid" ng-click="updateInstance()">Update</button>
            </div>
        </div>
    </ng-form>
</div>

@section scripts
{
    <script asp-append-version="true" src="~/assets/js/angular.min.js"></script>
    <script asp-append-version="true" src="~/appscript/common/ui-bootstrap-tpls-1.0.0.min.js"></script>

    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.min.js"></script>
    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.tpls.min.js"></script>
    <script asp-append-version="true" src="~/appScript/common/angular-common.js"></script>

    <script asp-append-version="true" src="~/appscript/appscriptdatepicker.js"></script>
    <script asp-append-version="true" src="~/appscript/model.js"></script>
    <script asp-append-version="true" src="~/appscript/instancesetup/instancesetupservice.js"></script>
    <script asp-append-version="true" src="~/appscript/instancesetup/instancesetupeditctrl.js"></script>

<style>
    .size {
        margin-bottom: -22px !important;
    }
</style>

}

UI/HQue.WebCore/Views/InstanceSetup/_BranchEdit.cshtml
<script type="text/ng-template" id="EditBranch">

    <div class="popup-overlay form-popup">

        <div class="middlealign">
          Test
        </div>

    </div>

</script>

UI/HQue.WebCore/Views/InstanceSetup/_hCueSupportLogin.cshtml
<script type="text/ng-template" id="hCueSupportLoginTemplate">
    <div class="popup-overlay form-popup">
        <div class="middlealign">
            <div>
                <div id="hCueSupportLogin" class="popup-wrap reminder-popup alternate" style="border-color:#3DB29F;" modal="shouldBeOpen">
                    <div class="popup-close" ng-click="close('No')"><i class="fa fa-times"></i></div>
                    <h3 style="background-color:#28465a;">hCue Support Login</h3>
                    <ng-form id="hCueSupportLoginForm" name="hCueSupportLoginForm">
                        <div class="row popup-row form-data">
                            <div class="panel panel-default" style="margin-bottom:0px;">
                                <div class="panel-body p-12">
                                    <div class="form-group">
                                        <div class="user-ctrl">
                                            <input title="Email Id" ng-model="email" type="text" class="form-control ctrl" email required placeholder="Email ID" autofocus>

                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="pswd-ctrl">
                                            <input title="Password" placeholder="Password" ng-model="password" id="login-password" type="password" class="form-control ctrl" name="password" required>
                                        </div>
                                    </div>
                                    <div class="form-group" style="margin-bottom:0px;">
                                        <div class="list list-inset">
                                            <span class="list list-inset error-msg ng-binding ng-hide"></span>
                                        </div>
                                        <center><i class="ion-loading-c" ng-show="showloading" style="font-size:40px"></i></center>
                                        <input title="Login" ng-click="submit()" type="submit" id="btn-login" class="btn btn-primary pull-right" value="Login" style="background-color: #00c853;max-width:120px;" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </ng-form>
                </div>
            </div>
        </div>
    </div>
</script>
<style>
    #hCueSupportLogin {
        max-width: 400px !important;
    }

    .p-12 {
        padding-left: 12px;
        padding-right: 12px;
        padding-top: 15px;
        padding-bottom: 0px;
    }
</style>