UI/HQue.WebCore/Controllers/Accounts/CustomerReceiptController.cs
using Microsoft.AspNetCore.Mvc;
using Utilities.Helpers;

namespace HQue.WebCore.Controllers.Accounts
{
    [Route("[controller]")]
    public class CustomerReceiptController : BaseController
    {
        private readonly ConfigHelper _configHelper;
        public CustomerReceiptController(ConfigHelper configHelper) : base(configHelper)
        {
            _configHelper = configHelper;
        }

        [Route("[action]")]
        public IActionResult Index()
        {
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/Dashboard");
            }
            return View();
        }


        //[Route("[action]")]
        //public IActionResult CustomerDetails()
        //{
        //    return View();
        //}

        [Route("[action]")]
        public IActionResult Cheque()
        {
            return View();
        }

        [Route("[action]")]
        //Customer receipt shown by PatientId instead of patient mobile & name - Settu
        public IActionResult CustomerDetails(string PatientId)
        {
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/Dashboard");
            }

            ViewBag.PatientId = PatientId;
            return View();
        }
    }
}

UI/HQue.WebCore/Views/CustomerReceipt/Cheque.cshtml
@{
    ViewBag.Title = "Cheque";
    ViewBag.Menu = "Accounts";
}
@await Html.PartialAsync("~/Views/Payment/Menu.cshtml")


<div class="row panelBorder paymentList" ng-app="hcue" ng-controller="ChequeReceiptCtrl " ng-cloak>

    <div class="panel panel-default" style="margin-top: 15px;border-radius: 4px;">
        <div class="panel-body" style="padding: 7px 10px 12px;">
            <div class='row'>
                <div class='col-sm-12 pull-left trim-left override_margin' style="height:100px;">
                    <div class='form-group col-sm-12 override_margin'>
                        <div class="input-group col-sm-2 pull-left sell-group-decor override_margin">
                            <label>Customer Name</label>
                            <input type="text" ng-model="selectedCustomer"
                                   typeahead-focus-on-select="false"
                                   typeahead-min-length="1"
                                   placeholder="Customer Name"
                                   title="Customer Name"
                                   typeahead-on-select="onCustomerSelect()"
                                   typeahead-editable="false"
                                   uib-typeahead="customer as customer.name for customer in getCustomers($viewValue,'name')"
                                   class="form-control form-control-small"
                                   typeahead-template-url="itemTpl.html"
                                   ng-enter="customerChequeSearch()"
                                   typeahead-no-results="NoCustomer"
                                   typeahead-loading="LoadingCustomers" />
                            <script type="text/ng-template" id="itemTpl.html">
                                <a tabindex="-1">
                                    <span ng-bind-template="{{match.model.name}}  ({{match.model.mobile}})"></span>
                                </a>
                            </script>
                            <i ng-show="LoadingCustomers" class="glyphicon glyphicon-refresh">Loading..</i>
                            <div ng-show="NoCustomer">
                                <i class="glyphicon glyphicon-remove">
                                </i> No Results Found
                            </div>
                        </div>
                        <div class="col-sm-2 input-group sell-group-decor">
                            <label>Mobile No</label>
                            <input type="text" ng-model="selectedCustomer"
                                   typeahead-focus-on-select="false"
                                   typeahead-min-length="1"
                                   placeholder="Customer Mobile"
                                   title="Customer Mobile"
                                   ng-keydown="checkNumber()"
                                   typeahead-on-select="onCustomerSelect()"
                                   typeahead-editable="false"
                                   uib-typeahead="customer as customer.mobile for customer in getCustomers($viewValue,'mobile')"
                                   class="form-control form-control-small"
                                   typeahead-template-url="itemTpl.html"
                                   ng-enter="customerChequeSearch()"
                                   typeahead-no-results="NoMobile"
                                   typeahead-loading="LoadingMobile"
                                   id="txtMobile" />
                            <script type="text/ng-template" id="itemTpl.html">
                                <a tabindex="-1">
                                    <span ng-bind-template="{{match.model.name}}  ({{match.model.mobile}})"></span>
                                </a>
                            </script>
                            <i ng-show="LoadingMobile" class="glyphicon glyphicon-refresh">Loading..</i>
                            <div ng-show="NoMobile">
                                <i class="glyphicon glyphicon-remove">
                                </i> No Results Found
                            </div>
                            <span class="error" style="margin-left:0px;" ng-bind="showCustomerWarn"></span>
                        </div>
                        <div class='col-sm-1 input-group sell-group-decor'>
                            <label class='col-md-12'>&nbsp;&nbsp;&nbsp;&nbsp;</label>
                            <button title="Search" ng-disabled="selectedCustomer == null" class="btn btn-style" type="button" ng-click="customerChequeSearch()">
                                SEARCH
                            </button>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

    <div>
        <span class="col-sm-12  override_margin pull-left">
            <span class="col-sm-4 override_margin">
                <strong>
                    <span style="color:#6E6E6E">
                        Total:
                    </span>
                    <i class="fa fa-rupee" title="Total"></i>
                    <span style="font-size:18px;">{{totalAmount | number:2}}</span>
                </strong>
            </span>



            <span class="col-sm-4 override_margin">
                <strong>
                    <span style="color:#6E6E6E">
                        Name:
                    </span>

                    <span style="font-size:18px;">{{name}}</span>
                </strong>
            </span>



            <span class="col-sm-4 override_margin">
                <strong>
                    <span style="color:#6E6E6E">
                        Mobile:
                    </span>

                    <span style="font-size:18px;">{{mobile}}</span>
                </strong>
            </span>

        </span>
    </div>



    <div class="panel panel-default">
        <div class="col-sm-12" style="padding:0;">
            <div class="panel">
                <div class="panel-body orange-border-top list-wrapper" style="padding: 4px;">
                    <div class="row">
                        <div class="row tblHeader">
                            <span class="col-sm-12 pull-left">
                                <span class="col-sm-2 col-sm-offset-1 pull-left invoice-number text-center">
                                    <span class="orange-text payment-color" style="float:none;" title="Invoice No"><strong>Bill No</strong></span>
                                </span>
                                <span class="col-sm-2 pull-left invoice-details text-center">
                                    <span title="Invoice Date" style="float:none;" class="invoice-date payment-color"><strong>Bill Date</strong></span>
                                </span>
                                <span class="col-sm-3 invoice-details text-center">
                                    <span style="width:100%;float:none;margin:0px;"><strong>Bill Amount</strong></span>
                                </span>
                                <span class="col-sm-3 invoice-details text-center">
                                    <span style="width:100%;float:none;margin:0px;"><strong>Type</strong></span>
                                </span>
                            </span>
                        </div>

                        <div ng-repeat="item in list track by $index">
                            <div class="chip-style">
                                <span class="col-sm-12 pull-left">
                                    <span class="col-sm-1 pull-left">
                                        <button title="+" class="chip-btn" id="chip-btn{{$index}}" data="{{$index}}" ng-click="toggleProductDetail($event)">+</button>
                                    </span>
                                    <span class="col-sm-2 pull-left invoice-number text-center">
                                        <strong class="orange-text" style="float:none;" title="Invoice Series">{{item.invoiceSeries}}</strong><strong class="orange-text" title="Invoice No">{{item.invoiceNo}}</strong>
                                    </span>
                                    <span class="col-sm-2 pull-left invoice-details text-center">
                                        <span title="Invoice Date" class="invoice-date" style="float:none;">{{item.invoiceDate | date:'dd/MM/yyyy'}}</span>
                                    </span>
                                    <span class="col-sm-3 pull-left invoice-details text-center">
                                        <span class="invoice-date text-right" style="width:100%;float:none;margin:0px;"><i class="fa fa-rupee" title="Total"></i> {{item.amount | number:2}}</span>
                                    </span>
                                    <span class="col-sm-3 pull-left invoice-details text-center">
                                        <span class="invoice-date text-right" style="width:100%;float:none;margin:0px;">{{item.type}}</span>
                                    </span>
                                </span>
                            </div>

                            <div class="chips-wrapper" style="overflow: hidden; display: none;" id="chip-wrapper{{$index}}">
                                <table class="table payment-tbl">
                                    <thead>
                                        <tr>
                                            <th>Cheque Date</th>
                                            <th>Cheque Number</th>
                                            <th class="text-center">Bank Deposited</th>
                                            <th class="text-center">Amount Credited</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        <tr>
                                            <td>{{item.chequeDate | date:'dd/MM/yyyy'}}</td>
                                            <td>{{item.chequeNo}}</td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" ng-disabled="!item.isEdit" ng-model="item.bankDeposited" />
                                            </td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" ng-disabled="!item.isEdit" ng-model="item.amountCredited" />
                                            </td>
                                            <td>

                                                <span class="col-md-1 glyphicon glyphicon-edit cross-icon" style="cursor: pointer;" title="Edit" ng-click="EditItem($index)" ng-hide="item.isEdit"></span>


                                                @*<button class="btn btn-style" ng-disabled="item.isEdit" ng-click="EditItem($index)">Edit</button>*@
                                                <button class="btn btn-style" ng-disabled="!item.isEdit" ng-click="SaveItem(item,$index)">Save</button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




</div>




@section scripts
{
    <script asp-append-version="true" src="~/assets/js/angular.js"></script>
    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.min.js"></script>
    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.tpls.min.js"></script>
    <script asp-append-version="true" src="~/appscript/common/angular-common.js"></script>
    <script asp-append-version="true" src="~/appscript/accounts/payment/paymentappscript.js"></script>
    <script asp-append-version="true" src="~/appscript/model.js"></script>
    <script asp-append-version="true" src="~/appscript/accounts/customerreceipt/customerreceiptservice.js"></script>

    <script asp-append-version="true" src="~/appscript/accounts/customerreceipt/ChequeReceiptCtrl.js"></script>


    <script asp-append-version="true" src="~/appscript/common/ui-bootstrap-tpls-1.0.0.min.js"></script>
    <script asp-append-version="true" src="~/lib/angular-chosen-localytics/chosen.js"></script>
    <script asp-append-version="true" src="~/lib/chosen/chosen.jquery.js"></script>
    <link asp-append-version="true" href="~/lib/chosen/chosen.css" rel="stylesheet" />
    <link asp-append-version="true" href="~/lib/angular-chosen-localytics/chosen-spinner.css" rel="stylesheet" />

}

UI/HQue.WebCore/Views/CustomerReceipt/Index.cshtml
@{
    ViewBag.Title = "Customer Receipts";
    ViewBag.Menu = "Accounts";
}

@await Html.PartialAsync("~/Views/Payment/Menu.cshtml")

<div class="row panelBorder paymentList" ng-app="hcue" ng-controller="customerReceiptSearchCtrl " ng-cloak>
    <div class="panel panel-default" style="margin-top: 15px;border-radius: 4px;">
        <div class="panel-body" style="padding: 7px 10px 12px;">
            <div class='row'>
                <div class='col-sm-12 pull-left trim-left override_margin'>
                    <div class='form-group col-sm-12 override_margin'>
                        <div class="input-group col-sm-2 pull-left sell-group-decor override_margin">
                            <label>Customer Name</label>
                            <select chosen
                                    title="Customer Name"
                                    option="vendorList"
                                    data-placeholder="Select Customer"
                                    ng-model="selectedCustomer"
                                    ng-options="option.customerName for option in Filterlist track by option.customerName"
                                    ng-change="changeCustomerName(selectedCustomer)"
                                    class="form-control">
                                <option value=""></option>
                            </select>
                        </div>
                        <div class="col-sm-2 input-group sell-group-decor">
                            <label>Mobile No.</label>
                            <input placeholder="Mobile" id="searchPatientMobile" maxlength="15" type="text" class="search-query form-control" ng-keyup="keyEnter($event,'drugName')" ng-model="patientSearchData.mobile" ng-change="changeMobileNumber(patientSearchData.mobile)" ng-enter="changeMobileNumber(patientSearchData.mobile)" valid-number ng-disabled="disableCustomerMobile" />

                            <span class="error" style="margin-left:0px;" ng-bind="showCustomerWarn"></span>


                        </div>
                        <div class='col-sm-1 input-group sell-group-decor'>
                            <label class='col-md-12'>&nbsp;&nbsp;&nbsp;&nbsp;</label>
                            <button title="Search" class="btn btn-style" type="button" ng-click="Filterdata(patientSearchData.mobile)">
                                SEARCH
                            </button>
                        </div>
                       
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div>
        <span class="col-sm-12  override_margin pull-left">

            <span class="col-sm-12 override_margin">

                <strong>
                    <span style="color:#6E6E6E">
                        Total Due:
                    </span> <span style="font-size:18px;">{{(totalDue | number:2)}}</span>
                </strong>

            </span>
        </span>
    </div>
    <div class="panel panel-default">
        <div class="col-sm-12" style="padding:0;">
            <div class="panel">
                <div class="panel-body orange-border-top list-wrapper" style="padding: 4px;">
                    <div class='row'>
                        <div class="row tblHeader">
                            <span class="col-sm-12 pull-left">

                                <span class="col-sm-3 pull-left invoice-number">
                                    <span class="orange-text payment-color" title="Invoice No"><strong>Customer Name</strong></span>
                                </span>
                                <span class="col-sm-3 pull-left invoice-details">
                                    <span title="Invoice Date" class="invoice-date payment-color"><strong>Mobile No</strong></span>
                                </span>
                                <span class="col-sm-2 pull-left invoice-details">
                                    <span title="Total" class="payment-price payment-color"><strong>Due</strong></span>
                                </span>
                                <span class="col-sm-2 pull-left invoice-details">
                                    <span title="Total" class="payment-price payment-color"><strong>Balance</strong></span>
                                </span>
                                <span class="col-sm-2 pull-left invoice-details">
                                    <span title="Total" class="payment-price payment-color"><strong></strong></span>
                                </span>
                            </span>
                        </div>
                        <div ng-repeat="sales in list">
                            <div class="chip-style">
                                <span class="col-sm-12 pull-left">
                                    <span class="col-sm-3 pull-left invoice-number">
                                        <strong class="orange-text txtUpper" title="Invoice No"> {{sales.customerName}}</strong>
                                    </span>
                                    <span class="col-sm-3 pull-left invoice-details">
                                        <span title="Invoice Date" class="invoice-date">{{sales.customerMobile }}</span>
                                    </span>
                                    <span class="col-sm-2 pull-left invoice-details">
                                        <span title="Total" class="payment-price"><i class="fa fa-rupee" title="Total"></i>{{(sales.customerCredit -sales.customerDebit)  | number:2}}</span>
                                    </span>
                                    <span class="col-sm-2 pull-left invoice-details">
                                        <span title="Total" class="payment-price"><i class="fa fa-rupee" title="Total"></i>{{(sales.balanceAmount)  | number:2}}</span>
                                    </span>
                                    <span class="col-sm-2 pull-left invoice-details">
                                        <a class="col-md-12 text-center" ng-href="/customerReceipt/customerDetails?PatientId={{sales.sales.patientId}}" style="" title="Return">View Details</a>
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    div.chip-style {
        border-top: 0px solid #EBEAEA;
        border-left: 0px solid #EBEAEA;
        border-right: 0px solid #EBEAEA;
        border-bottom: 1px solid #EBEAEA;
        background-color: #FFF;
        margin-top: 0px;
        padding: 9px 3px;
    }

    .chosen-container {
        width: 100% !important;
    }
</style>
@section scripts
{
    <script asp-append-version="true" src="~/assets/js/angular.min.js"></script>
    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.min.js"></script>
    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.tpls.min.js"></script>
    <script asp-append-version="true" src="~/appscript/common/angular-common.js"></script>
    <script asp-append-version="true" src="~/appscript/accounts/payment/paymentappscript.js"></script>
    <script asp-append-version="true" src="~/appscript/model.js"></script>
    <script asp-append-version="true" src="~/appscript/accounts/customerreceipt/customerreceiptservice.js"></script>
    <script asp-append-version="true" src="~/appscript/accounts/customerreceipt/customerreceiptsearchctrl.js"></script>

    <script asp-append-version="true" src="~/appscript/common/ui-bootstrap-tpls-1.0.0.min.js"></script>
    <script asp-append-version="true" src="~/lib/angular-chosen-localytics/chosen.js"></script>
    <script asp-append-version="true" src="~/lib/chosen/chosen.jquery.js"></script>
    <link asp-append-version="true" href="~/lib/chosen/chosen.css" rel="stylesheet" />
    <link asp-append-version="true" href="~/lib/angular-chosen-localytics/chosen-spinner.css" rel="stylesheet" />

}

UI/HQue.WebCore/Views/CustomerReceipt/Menu.cshtml
<ul class="nav nav-tabs override_margin">
    <li class="@(ViewBag.Title == "Petty Cash" ? "active" : "")">
        <a asp-action="Index" asp-controller="PettyCash">
            Petty Cash
        </a>
    </li>
    <li class="@(ViewBag.Title == "Customer Receipts" ? "active" : "")">
        <a asp-action="Index" asp-controller="CustomerReceipt">
            Customer Receipts
        </a>
    </li>
    <li class="@(ViewBag.Title == "Payment" ? "active" : "")">
        <a asp-action="Index" asp-controller="Payment">
            Vendor Payments
        </a>
    </li>
    <li class="@(ViewBag.Title == "Settings" ? "active" : "")">
        <a asp-action="Index" asp-controller="PettyCashSettings">
            Settings
        </a>
    </li>
</ul>