UI/HQue.WebCore/Controllers/Inventory/ProductStockController.cs
using HQue.Biz.Core.Inventory;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Utilities.Helpers;

namespace HQue.WebCore.Controllers.Inventory
{
    [Route("[controller]")]
    public class ProductStockController : BaseController
    {
        private readonly ProductStockManager _productStockManager;
        private readonly ConfigHelper _configHelper;
        public ProductStockController(ConfigHelper configHelper, ProductStockManager productStockManager) : base(configHelper)
        {
            _configHelper = configHelper;
            _productStockManager = productStockManager;
        }

        [Route("[action]")]
        public async Task<IActionResult> List()
        {
            ViewBag.IsBarcodeEnabled = await _productStockManager.GetFeatureAccess(1);
            return View();
        }

        [Route("[action]")]
        public async Task<IActionResult> UpdateInventory()
        {
            ViewBag.IsBarcodeEnabled = await _productStockManager.GetFeatureAccess(1);
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/ProductStock/List");
            }
            return View();
        }

        [Route("[action]")]
        public async Task<IActionResult> ProductList()
        {
            ViewBag.IsBarcodeEnabled = await _productStockManager.GetFeatureAccess(1);
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/ProductStock/List");
            }
            return View();
        }

        [Route("[action]")]
        public async Task<IActionResult> InventorySetting()
        {
            ViewBag.IsBarcodeEnabled = await _productStockManager.GetFeatureAccess(1);
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/ProductStock/List");
            }
            return View();
        }

        [Route("[action]")]
        public async Task<IActionResult> ProductMaster()
        {
            ViewBag.IsBarcodeEnabled = await _productStockManager.GetFeatureAccess(1);
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/ProductStock/List");
            }
            return View();
        }

        [Route("[action]")]
        public async Task<IActionResult> SelfConsumption()
        {
            ViewBag.IsBarcodeEnabled = await _productStockManager.GetFeatureAccess(1);
            var testOffline = User.OfflineStatus();
            if (_configHelper.AppConfig.OfflineMode == false && testOffline == "True")
            {
                Response.Redirect("/ProductStock/List");
            }
            return View();
        }

        [Route("[action]")]
        public async Task<IActionResult> BarcodeProfile()
        {
            ViewBag.IsBarcodeEnabled = await _productStockManager.GetFeatureAccess(1);
            if (ViewBag.IsBarcodeEnabled == true)
            {
                return View();
            }
            else
            {
                return View("Rights");
            }
        }

        [Route("[action]")]
        public async Task<IActionResult> BarcodePRNDesign()
        {
            ViewBag.IsBarcodeEnabled = await _productStockManager.GetFeatureAccess(1);
            if (ViewBag.IsBarcodeEnabled == true)
            {
                return View();
            }
            else
            {
                return View("Rights");
            }
        }

        [Route("[action]")]
        public async Task<IActionResult> BarcodeGeneration()
        {
            ViewBag.IsBarcodeEnabled = await _productStockManager.GetFeatureAccess(1);
            if (ViewBag.IsBarcodeEnabled == true)
            {
                return View();
            }
            else
            {
                return View("Rights");
            }
        }

    }
}

UI/HQue.WebCore/Views/ProductStock/BarcodePRNDesign.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Barcode PRN Design";
    Layout = "_Layout";
}
@await Html.PartialAsync("~/Views/ProductStock/Menu.cshtml")

<div class="row panelBorder" ng-app="hcue" ng-controller="barcodePRNDesignCtrl" ng-cloak>
    <div class="row">
        <h4 class="margin">Barcode PRN Field Mapping</h4>
    </div>
    <div class="panel panel-default">
        <div class="panel-body override_margin">
            <div class="row margin-top-10">
                <div class="col-md-2 margin-top-10">
                    <label>Barcode PRN Design Name</label>
                </div>
                <div class="col-md-3 input-group override_margin">
                    <input 
                           type="text" 
                           title="Enter Barcode PRN Design Name" 
                           ng-model="prnDesign.prnName" 
                           ng-enter="setFocus('selectBarcodePRNDesignFile')" 
                           placeholder="Enter Barcode PRN Design Name" 
                           class="form-control" 
                           id="barcodePRNDesignName" 
                           typeahead-focus-on-select="false"
                           typeahead-min-length="1"
                           required
                           typeahead-on-select="onSelect(prnDesign.prnName)"
                           uib-typeahead="prnDesign as prnDesign.prnName for prnDesign in getPrnDesignList($viewValue)"/>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-md-2 padding-right-0 margin-top-10">
                    <label>Select Barcode PRN Design File</label>
                </div>
                <div class="col-md-3 override_margin">
                    <input type="file" title="Select Barcode PRN Design File" onchange="pressed()" ng-enter="browseFile()" class="col-md-1 override_margin margin-top-8" id="selectBarcodePRNDesignFile" />
                    <label class="margin-top-11" id="lblPRNFile">Please Browse PRN File</label>                    
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-md-8 override_margin">
                    <table class="table table-bordered override_margin">
                        <thead>
                            <tr>
                                <th class="text-center">S. No</th>
                                <th class="text-center">Barcode Field</th>
                                <th class="text-center">PRN Field</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="data in prnDesign.prnFieldJson track by $index">
                                <td class="override_margin1">{{data.seqId}}</td>
                                <td class="override_margin1">
                                    {{data.field}} 
                                    <label ng-if="data.isMandatory" class="required"></label>
                                </td>
                                <td class="col-md-3 override_margin">
                                    <input type="text" maxlength="30" ng-enter="setFocus((($index+1)==prnDesign.prnFieldJson.length ? 'save' : 'prnField'+($index+1)))" id="prnField{{$index}}" ng-model="data.prnField" class="input-box-style" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row margin">
                <div class="col-md-8">
                    <div class="col-md-2 pull-right override_margin">
                        <button title="To {{mode=='NEW' ? 'Save' : 'Update'}} PRN Design" id="save" class="btn btn-small btn-style form-control" ng-click="savePRNDesign()">
                            {{mode=='NEW' ? 'Save' : 'Update'}}
                        </button>
                    </div>
                    <div class="col-md-2 pull-right override_margin">
                        <button title="Clear" class="btn btn-style btn-cancel form-control" ng-click="setData()">Clear</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @{
        await Html.RenderPartialAsync("_showConfirmMsg");
    }
</div>

<style>
    .input-box-style {
        width: 100%;
        padding-left: 5px;
    }
    .override_margin1 {
        padding: 4px 5px !important;
        margin: 0px !important;
    }
    .margin-top-10 {
        margin-top: 8px;
    }

    .margin-top-8 {
        margin-top: 5px !important;
    }

    .margin-top-11 {
        margin-top: 8px;
    }

    .margin {
        margin: 10px 0px 10px 5px;
    }

    .padding-right-0 {
        padding-right: 0px;
    }

    input[type=file] {
        width: 30%;
        color: transparent;
    }
</style>

@section scripts
{

    <script asp-append-version="true" src="/assets/js/angular.js"></script>
    <script asp-append-version="true" src="~/appScript/common/angular-common.js"></script>
    <script asp-append-version="true" src="~/appscript/common/ui-bootstrap-tpls-1.0.0.min.js"></script>

    <script asp-append-version="true" src="~/AppScript/Barcode/barcodeAppScript.js"></script>
    <script asp-append-version="true" src="~/AppScript/Barcode/barcodePRNDesignCtrl.js"></script>
    <script asp-append-version="true" src="~/appscript/productStock/productStockservice.js"></script>

    <script asp-append-version="true" src="~/appscript/angular-modal-service.js"></script>
    <script asp-append-version="true" src="~/AppScript/common/showConfirmMsgCtrl.js"></script>
    <link asp-append-version="true" href="~/assets/css/reminder-extended.css" rel="stylesheet" />

}

UI/HQue.WebCore/Views/ProductStock/BarcodeProfile.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Barcode Profile";
    Layout = "_Layout";
}
@await Html.PartialAsync("~/Views/ProductStock/Menu.cshtml")

<div class="row panelBorder" ng-app="hcue" ng-controller="barcodeProfileCtrl" ng-cloak>
    <div class="row">
        <h4 class="margin">Barcode Profile Creation</h4>
    </div>
    <div class="panel panel-default">
        <div class="panel-body override_margin">
            <div class="row margin-top-10">
                <div class="col-md-2 margin-top-10">
                    <label>Barcode Profile Name</label>
                </div>
                <div class="col-md-3 input-group override_margin">
                    <input type="text"
                           title="Enter Barcode Profile Name"
                           placeholder="Enter Barcode Profile Name"
                           class="form-control"
                           id="barcodeProfileName"
                           ng-enter="setFocus('defaultProfile')"
                           ng-model="profile.profileName"
                           typeahead-focus-on-select="false"
                           typeahead-min-length="1"
                           required
                           typeahead-on-select="onSelect(profile.profileName)"
                           uib-typeahead="profile as profile.profileName for profile in getProfileList($viewValue)" />
                </div>
                <div class="col-md-5 form-group">
                    <input type="checkbox" id="defaultProfile" ng-model="profile.isDefaultProfile" ng-enter="setFocus('setYesNo0')" class="pull-left margin-top-10" title="Default Profile will be selected automatically in Barcode Generation & Printing screen" />
                    <h5 class="margif-left-5">Set as Default Profile</h5>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-md-8 override_margin">
                    <table class="table table-bordered override_margin">
                        <thead>
                            <tr>
                                <th class="text-center">S. No</th>
                                <th class="text-center">Settings</th>
                                <th class="text-center">Set[Y/N]</th>
                                <th class="text-center">Order</th>
                                <th class="text-center">Max Length</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="data in profile.profileJson track by $index">
                                <td>{{data.seqId}}</td>
                                <td>{{data.field}}</td>
                                <td class="col-md-2 override_margin">
                                    <input ng-disabled="profile.isTransactedProfile" type="text" ng-model="data.setYesNo" id="setYesNo{{$index}}" ng-enter="setFocus('order'+$index)" ng-change="setYesNo(data)" maxlength="1" class="form-control txtUpper" />
                                </td>
                                <td class="col-md-2 override_margin">
                                    <input ng-disabled="profile.isTransactedProfile" type="text" id="order{{$index}}" numbers-only valid-number maxlength="2" ng-enter="setFocus('maxLength'+$index)" ng-model="data.order" ng-change="setOrder(data)" class="form-control" />
                                </td>
                                <td class="col-md-2 override_margin">
                                    <input ng-disabled="profile.isTransactedProfile" type="text" id="maxLength{{$index}}" numbers-only valid-number maxlength="2" ng-enter="setFocus((($index+1)==profile.profileJson.length ? 'save' : 'setYesNo'+($index+1)))" ng-model="data.maxLength" ng-change="setMaxLength(data)" class="form-control" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-4">
                    <label>Note:</label>
                    <ul>
                        <li>0/1 will be added as first character in barcode. 0 as Online & 1 as Offline. It will not be added in product wise barcode generation</li>
                        <li>Sequence number will be added as last character in barcode.</li>
                        <li>Sequence number will not be added for product wise barcode generation.</li>
                        <li>Branch code will be added before sequence number in barcode.</li>
                    </ul>
                </div>
            </div>
            <div class="row margin">
                <div class="col-md-8 override_margin">
                    <div class="col-md-6 pull-left margin-top-10">
                        <ul>
                            <li>
                                <label style="color:red">Total maximum length should be less than or equal to {{totalMaxLength}}.</label>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-2 pull-right override_margin">
                        <button title="To {{mode=='NEW' ? 'Save' : 'Update'}} Profile" id="save" class="btn btn-small btn-style form-control" ng-click="saveProfile()">
                            {{mode=='NEW' ? 'Save' : 'Update'}}
                        </button>
                    </div>
                    <div class="col-md-2 pull-right override_margin">
                        <button title="Clear" class="btn btn-style btn-cancel form-control" ng-click="setData()">Clear</button>
                    </div>
                </div>
                <div class="col-md-4">
                    <label>Example Barcode for [Default Profile]: 0 00001 1234 1220 1 1</label>
                    <ul>
                        <li>0 is Online.</li>
                        <li>00001 is product code</li>
                        <li>1234 is last four characters of batch no</li>
                        <li>1220 is expiry date</li>
                        <li>1 is branch code</li>
                        <li>Last 1 is sequence number</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    @{
        await Html.RenderPartialAsync("_showConfirmMsg");
    }
</div>

<style>
    .margin-top-10 {
        margin-top: 10px !important;
    }

    .margin {
        margin: 10px 0px 10px 5px;
    }

    .margif-left-5 {
        margin-left: 16px !important;
    }
</style>

@section scripts
{

    <script asp-append-version="true" src="/assets/js/angular.js"></script>
    <script asp-append-version="true" src="~/appScript/common/angular-common.js"></script>
    <script asp-append-version="true" src="~/appscript/common/ui-bootstrap-tpls-1.0.0.min.js"></script>

    <script asp-append-version="true" src="~/AppScript/Barcode/barcodeAppScript.js"></script>
    <script asp-append-version="true" src="~/AppScript/Barcode/barcodeProfileCtrl.js"></script>
    <script asp-append-version="true" src="~/appscript/productStock/productStockservice.js"></script>

    <script asp-append-version="true" src="~/appscript/angular-modal-service.js"></script>
    <script asp-append-version="true" src="~/AppScript/common/showConfirmMsgCtrl.js"></script>
    <link asp-append-version="true" href="~/assets/css/reminder-extended.css" rel="stylesheet" />

}

UI/HQue.WebCore/Views/ProductStock/Menu.cshtml
@using HQue.Contract.Infrastructure.UserAccount
@using Utilities.Helpers
<ul class="nav nav-tabs override_margin">
    <li class="@(ViewBag.Title == "Inventory" ? "active" : "")">
        <a asp-action="List" asp-controller="ProductStock">
            INVENTORY
        </a>
    </li>
@if ((ViewBag.Config.AppConfig.OfflineMode == false && User.OfflineStatus() != "True") || ViewBag.Config.AppConfig.OfflineMode == true)
{
    <li class="@(ViewBag.Title == "Update Inventory" ? "active" : "")">
        <a asp-action="UpdateInventory" asp-controller="ProductStock">
            UPDATE INVENTORY
        </a>
    </li>
    @*@if (ViewBag.Config.AppConfig.IsSqlServer)
    {
        <li>
            <a href="/ExpireProductReport/list">EXPIRE PRODUCT REPORT</a>
        </li>
    }*@
    @if (User.HasPermission(UserAccess.Settings))
    {
        <li class="@(ViewBag.Title == "Inventory Setting" ? "active" : "")">
            <a asp-action="InventorySetting" asp-controller="ProductStock">
                INVENTORY SETTING
            </a>
        </li>
    }
    <li class="@(ViewBag.Title == "ProductMaster" ? "active" : "")">
        <a asp-action="ProductMaster" asp-controller="ProductStock">
            PRODUCT MASTER
        </a>
    </li>
    <li class="@(ViewBag.Title == "Self Consumption" ? "active" : "")">
        <a asp-action="SelfConsumption" asp-controller="ProductStock">
            SELF CONSUMPTION
        </a>
    </li>

    <a href="/Sales/Download" class="blink_me" title="new sales screen" style="color:#28465a;font-size:15px;float:right;margin-right:25px;text-decoration:none;" formmethod="get" formaction="Download" formtarget="_blank">* HSN Code Reference</a>
}

    @if (ViewBag.IsBarcodeEnabled == true)
    {
    <li class="dropdown @(ViewBag.Title == "Barcode Profile"
                || ViewBag.Title == "Barcode PRN Design"
                || ViewBag.Title == "Barcode Generation & Printing"
                ? "active" : "")">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Barcode&nbsp;&nbsp;<i class="fa fa-caret-down" aria-hidden="true"></i></a>
        <ul class="dropdown-menu">
            <li class="@(ViewBag.Title == "Barcode Profile" ? "active" : "")">
                <a asp-action="BarcodeProfile" asp-controller="ProductStock">Barcode Profile</a>
            </li>
            <li class="@(ViewBag.Title == "Barcode PRN Design" ? "active" : "")">
                <a asp-action="BarcodePRNDesign" asp-controller="ProductStock">Barcode PRN Design</a>
            </li>
            <li class="@(ViewBag.Title == "Barcode Generation & Printing" ? "active" : "")">
                <a asp-action="BarcodeGeneration" asp-controller="ProductStock">Barcode Generation & Printing</a>
            </li>
        </ul>
    </li>
    }

</ul>

UI/HQue.WebCore/Views/ProductStock/UpdateInventory01.cshtml
@{
    ViewBag.Title = "Update Inventory";
    Layout = "_Layout";
}

@await Html.PartialAsync("~/Views/ProductStock/Menu.cshtml")

<div class="row" ng-app="hcue" ng-controller="updateInventoryCtrl" ng-cloak>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class='row'>
                <div class='col-sm-6'>
                    <div class='form-group'>
                        <div class="input-group">
                            <div class='input-group col-sm-8' style="padding-left: 0px;">
                                <span class="input-group-addon front-addon">
                                    <img src="~/assets/images/drug.png" />
                                </span>
                                <angucomplete id="productName"
                                              placeholder="Search by Product"
                                              pause="400"
                                              selectedobject="selectedProduct"
                                              url="/ProductStockData/InStockProductList?productName="
                                              titleField="product.name"
                                              inputclass="search-query form-control"
                                              event="productSelected" />
                            </div>
                            <div class='input-group-btn col-sm-2' style="left:-30px">
                                <span class="input-group-btn">
                                    <button class="btn" type="button" ng-click="productStockSearch(null)">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>





    <div class="panel panel-default">
        <div class="panel-heading">Search Result</div>
        <div class="panel-body">
            <div class='row'>
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th class="text-center"><span class="glyphicon glyphicon-minus-sign"></span></th>
                            <th>Product Name</th>
                            <th>Batch No</th>
                            <th>Expire Date</th>
                            <th>Vat</th>
                            <th>Stock</th>
                            <th>Update Stock</th>
                            <th>Change</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="item in list" ng-form="editInventory">
                            <td class="text-center">
                                <span style="cursor: pointer;" title="Update Stock" ng-hide="editInventory.stock.$dirty && editInventory.stock.$error.required" class="edit-done-btn" ng-click="updateStock(item)"><img src="~/assets/images/done.png" width="25px" /></span>
                            </td>
                            <td>{{item.product.name}}</td>
                            <td>{{item.batchNo}}</td>
                            <td>{{item.expireDate | date:'dd/MM/yyyy' }}</td>
                            <td>{{item.vat}}</td>
                            <td>{{item.stock}}</td>
                            <td>
                                <input type="text" id="stock" style="width:100px" name="stock" placeholder="Stock" required ng-model="item.actualStock" valid-number>
                                <span class="error" ng-show="editInventory.stock.$dirty && editInventory.stock.$error.required">Required</span>
                            </td>
                            <td>{{item.actualStock - item.stock}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script asp-append-version="true" src="~/assets/js/angular.min.js"></script>
    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.min.js"></script>
    <script asp-append-version="true" src="~/lib/angular-toastr/dist/angular-toastr.tpls.min.js"></script>
    <script asp-append-version="true" src="~/appScript/common/angular-common.js"></script>

    <script asp-append-version="true" src="~/appscript/productStock/productStockappscript.js"></script>
    <script asp-append-version="true" src="~/appscript/model.js"></script>
    <script asp-append-version="true" src="~/appscript/productStock/productStockservice.js"></script>
    <script asp-append-version="true" src="~/appscript/productstock/updateinventoryctrl.js"></script>

    <link asp-append-version="true" href="~/lib/angucomplete/angucomplete.css" rel="stylesheet" />
    <script asp-append-version="true" src="~/appscript/common/angucomplete.js"></script>
}